-- AlterTable
ALTER TABLE `rapport_roles` MODIFY `role` ENUM('TOUS', 'ADMIN', 'MAIRE', 'ADJOINT_MAIRE', 'SECRETAIRE_COMMUNAL', 'ARCHIVISTE', 'ETAT_CIVIL', 'TRESORERIE', 'PERCEPTEUR', 'REGISSEUR') NOT NULL;

-- AlterTable
ALTER TABLE `users` MODIFY `role` ENUM('TOUS', 'ADMIN', 'MAIRE', 'ADJOINT_MAIRE', 'SECRETAIRE_COMMUNAL', 'ARCHIVISTE', 'ETAT_CIVIL', 'TRESORERIE', 'PERCEPTEUR', 'REGISSEUR') NOT NULL DEFAULT 'ETAT_CIVIL',
    MODIFY `proposedRole` ENUM('TOUS', 'ADMIN', 'MAIRE', 'ADJOINT_MAIRE', 'SECRETAIRE_COMMUNAL', 'ARCHIVISTE', 'ETAT_CIVIL', 'TRESORERIE', 'PERCEPTEUR', 'REGISSEUR') NULL;
